### ISSUE TITLE
Typescript: useFieldArray second argument (config) should be optional

### ISSUE THREAD

**Issue by Yankovsky** [final-form/react-final-form-arrays#104]
```
export function useFieldArray<
  FieldValue = any,
  T extends HTMLElement = HTMLElement
>(
  name: string,
  config: UseFieldArrayConfig<FieldValue>
): FieldArrayRenderProps<FieldValue, T>
```

config should be optional, right? Just like in react-final-form. Readme clearly states
> The useFieldArray hook takes two parameters, the first is the name of the field, and the second is an optional object that looks just like FieldArrayProps, except without the name. It returns an object just like FieldArrayRenderProps.

I'll make a pr.

**Comment by erikras** [comment]
Published fix in [`v3.1.1`](https://github.com/final-form/react-final-form-arrays/releases/tag/v3.1.1).
