### ISSUE TITLE
React 16.13.0 Warning: `Cannot update a component...` warning on push mutator

### ISSUE THREAD

**Issue by mikerudenko** [final-form/react-final-form-arrays#126]
### Are you submitting a **bug report** or a **feature request**?
 **bug report**

### What is the current behavior?
When I trying to trigger the push method to add f.e. todo item in my array I see this warning
`Warning: Cannot update a component from inside the function body of a different component.`

### What is the expected behavior?
No warning. On version 16.12.0 no warning happened

### What's your environment?
Chrome 80
MacOS Catalina
React 
16.13.0

**Comment by dominikzogg** [comment]
https://github.com/final-form/final-form-arrays/issues/50

**Comment by mikebarkmin** [comment]
React 16.13.0 introduced a new warning: https://reactjs.org/blog/2020/02/26/react-v16.13.0.html#warnings-for-some-updates-during-render

This warning is also discussed in react-final-form: https://github.com/final-form/react-final-form/issues/751

**Comment by mikerudenko** [comment]
In the future, I think a better approach will be this lib- https://react-hook-form.com/
No render props, only hooks,

**Comment by erikras** [comment]
> No render props, only hooks

@mikerudenko Also uncontrolled inputs, so no realtime validation. Engineering is a series of trade-offs.

**Comment by erikras** [comment]
Published a fix in [`react-final-form@6.4.0`](https://github.com/final-form/react-final-form/releases/tag/v6.4.0) and [`final-form@4.19.0`](https://github.com/final-form/final-form/releases/tag/v4.19.0). That should fix this issue.
