### ISSUE TITLE
Update peerDependencies to support React 18

### ISSUE THREAD

**Issue by bdbvb** [final-form/react-final-form-arrays#169]
### What is the current behavior?

Currently only supports React up to 17.

### What is the expected behavior?

Support React 18

(Seems to run OK with 18 - see link below - but causes an error on npm update, unless you use --force)

### Sandbox Link

https://codesandbox.io/s/react-final-form-field-arrays-forked-u3z0x6?file=/index.js

### What's your environment?

"final-form": "4.20.7"
"final-form-arrays": "3.0.2"
"react": "18.1.0"
"react-dom": "18.1.0"
Windows
Chrome
Node 16.14.0

**Comment by sudkumar** [comment]
I tried patch-packages as well but it is not the right tool so I went with the --legacy-peer-deps.

I didn't know about the override thing. Thank you so much for sharing.

**Comment by sudkumar** [comment]
> I still had trouble when manually updating the peer dependency in react-final-form-arrays to include 18.x, so I'm not sure if that's all that has to change.

BTW, @bdbvb What trouble are you facing after manually updating deps. 

If that is the case then, there might be some issue with my application.  😄

> **Note** `fields.insert` function is already broken.

**Comment by bdbvb** [comment]
@erikras Is there any plan to upgrade react-final-form-arrays to support React 18?

**Comment by bdbvb** [comment]
This was fixed with version 3.1.4 and can be closed.
