### ISSUE TITLE
Typescript error for FieldArrayProps

### ISSUE THREAD

**Issue by davincho** [final-form/react-final-form-arrays#17]
### Are you submitting a **bug report** or a **feature request**?

bug report

### What is the current behavior?

**FieldArrayProps** is included from _final-form_ and throws an error
```
/node_modules/final-form/dist/index has no exported member 'FieldArrayProps'  
```

https://github.com/final-form/react-final-form-arrays/blob/32367dce89037cab1b79847ce8dd28522f87add4/src/index.d.ts#L2

### What is the expected behavior?

Should not throw Typescript exception, but it looks like FieldArrayProps does not exist in https://github.com/final-form/final-form/blob/master/src/index.d.ts

**Comment by rosskevin** [comment]
I'll take a shot at this one @erikras and add some tests.  If you can fix the build issue https://github.com/final-form/final-form-arrays/issues/7 that will be helpful.
