### ISSUE TITLE
Does not work with React 15

### ISSUE THREAD

**Issue by blairio** [final-form/react-final-form-arrays#20]
### Are you submitting a **bug report** or a **feature request**?

A Bug report

### What is the current behavior?

The package.json allows a peer of react 15, but it does not work with React 15.
The simple example fails with
```
Invariant Violation
ReactFinalFormFieldArray(4.2.0)(undefined).render(): A valid React element (or null) must be returned. You may have returned undefined, an array or some other invalid object.
```
### What is the expected behavior?

It works

### Sandbox Link

https://codesandbox.io/s/olq4xrrz05

### What's your environment?

"react-final-form-arrays": "1.0.3",
"react-final-form": "3.1.0",
"react-dom": "15.6.2",
"react": "15.6.2",
"final-form-arrays": "1.0.4",
"final-form": "4.2.0"

**Comment by erikras** [comment]
Well, the problem is that you are not returning anything from the render function when the array is empty. Changing it to this fixes it:
```jsx
<FieldArray name="customers">
  {({ fields }) =>
    fields.length
      ? fields.map((name, index) => (
          <div key={name}>
            // Fields here
          </div>
        ))
      : <div/>
  }
</FieldArray>
```
Not really a bug in this library, I don't think.
