### ISSUE TITLE
field.move causes an error when applied to two objects with different fields

### ISSUE THREAD

**Issue by dekhanov** [final-form/react-final-form-arrays#39]
### What is the current behavior?
`field.move` causes an error at the getValidators function when applied to two objects with different fields

See the demo: https://codesandbox.io/s/x94j811oj4
Click a `swap` button

### What is the expected behavior?
To swap objects with no error

### What's your environment?
See the CodeSandBox link

**Comment by luishdz1010** [comment]
Any workaround]? I'm hitting this with nested array fields...

**Comment by HawiCaesar** [comment]
I managed to make a simple workaround borrowing from @dekhanov example. I think it can be made better though I still find it readable. Here is the [demo](https://codesandbox.io/s/94lmn1xq3r).

This came with the inspiration of this [blog](https://medium.com/@erikras/final-form-arrays-and-mutators-13159cb7d285). Credits to Erik Rasmussen for explaining the mutator concept to detail.

**Comment by dekhanov** [comment]
Hi, @HawiCaesar! I,m afraid that what you have implemented is a `swap` mutator, not `move`.
There is no difference between them in the case of two elements, but it will not work correctly if the number of elements more then two.

@luishdz1010 
To workaround the issue you can try the first implementation of the `move` mutator from here:  https://github.com/final-form/final-form-arrays/commit/47505068631d2d31c6c8acaa6eda4ddcc4b3ee99#diff-2dda6a27cd50646eb66a941de8781bcf

In this case you will face this issue: https://github.com/final-form/final-form-arrays/issues/10
It's just a lesser of two evils.
