### ISSUE TITLE
Extend from React.Component (instead of React.PureComponent)

### ISSUE THREAD

**Issue by petermikitsh** [final-form/react-final-form-arrays#41]
### Are you submitting a **bug report** or a **feature request**?

Eh, this feels kind of somewhere in the middle.

### What is the current behavior?

FieldArray extends React.PureComponent.

### What is the expected behavior?

FieldArray extends React.Component.

### Sandbox Link

N/A

### What's your environment?

N/A

### Other information

For the reasons discussed in https://github.com/final-form/react-final-form/issues/150, I'd like to see parity across all `react-final-form*` packages.

The tl,dr: I have external state I feed into my FieldArray render component. I also have to explicitly pass this state to FieldArray as a prop, so the component re-renders.

**Comment by erikras** [comment]
Published in [`v1.1.0`](https://github.com/final-form/react-final-form-arrays/releases/tag/v1.1.0).
