### ISSUE TITLE
`dirtySinceLastSubmit` is missing in meta

### ISSUE THREAD

**Issue by donrsh** [final-form/react-final-form-arrays#45]
Bug Report

As title, it seems the `dirtySinceLastSubmit` in final form `FieldState` is missing when reporting to `meta` of `FieldArray`. [Line 196](https://github.com/final-form/react-final-form-arrays/blob/master/src/FieldArray.js).

Or do I misunderstand something that the `meta` should not contains `dirtySinceLastSubmit`? 🤔

**Comment by erikras** [comment]
Published fix in [`v1.1.0`](https://github.com/final-form/react-final-form-arrays/releases/tag/v1.1.0).
