### ISSUE TITLE
Performance: Single change triggers complete form rerender.

### ISSUE THREAD

**Issue by KeKs0r** [final-form/react-final-form-arrays#51]
### Are you submitting a **bug report** or a **feature request**?
Its an observation that some performance relevant behaviour has changed between the documentation sandbox example and current library versions.

### What is the current behavior?
Whenever one row of the array is modified, the whole form is rerendered.
Example:  https://p41myp2q.codesandbox.io/ 
This is a fork of the official example, but with updated dependencies.

This can easily be observed when activating `highlight updates` in the React chrome extension
![image](https://user-images.githubusercontent.com/2970814/47862263-06772e00-ddf5-11e8-920d-008325c88084.png)

### What is the expected behavior?
Only the relevant row should be rerendered and not trigger a rerender for all fields.
Example: https://kx8qv67nk5.codesandbox.io/

### Sandbox Link
New dependencies, where the whole Form is rerendered: https://p41myp2q.codesandbox.io/
Original Example from documentation, where only the modified row is updated: https://kx8qv67nk5.codesandbox.io/

## Update I tested this with different versions
- Downgrading `react-final-form-array` and `final-form-array` to 1.0.0 does not change this behaviour
- Downgrading `final-form` to `3.1.0` and `react-final-form` to `2.2` does fix the problem

--> Maybe this behaviour was introduced by Final Form `4.x` or react final foem `3.x`

**Comment by taneba** [comment]
@KeKs0r 
You can use subscription api to avoid unnecessary updates. 
see: https://github.com/final-form/react-final-form-arrays#subscription-fieldsubscription

**Comment by KeKs0r** [comment]
The FieldArray field, is not the right level for this. Because, it theoretically needs to know about all of its items. But when chaning one of the Single fields, I only want to rerender the single field.

Or maybe I am understanding the subscriptions wrong. Could you give me an example to achieve the same rerender behaviour as in: https://kx8qv67nk5.codesandbox.io/

**Comment by taneba** [comment]
@KeKs0r 
Ok, here is my forked one and I added subscriptions: https://codesandbox.io/s/vmnq88nm67

You can see how the rerendering optimized by checking "Highlight Updates" in the React chrome extension. It shows only one field that you typing is rerendered. Also, the stringified JSON in the <pre> rerendered because I added `FormSpy` which subscribe values.
Is this exactly what you want to achieve?

**Comment by KeKs0r** [comment]
Yes this was, what I was looking for. I am wondering, whether I am losing some rerenders, that are expected? Such as for pristine etc.?

But it looks very promising.

**Comment by taneba** [comment]
> I am wondering, whether I am losing some rerenders, that are expected? Such as for pristine etc.?

Yes, if you don't set any properties to subscription then <Form /> or <FieldArray /> won't rerender by changing form state. That's how subscription works.

**Comment by KeKs0r** [comment]
Thank you for helping me out. I played around with the subscriptions and they are quite straight forward. I think mainly the object syntax had me slightly confused.
