### ISSUE TITLE
Using "remove" on an array row is not making form dirty

### ISSUE THREAD

**Issue by supersime** [final-form/react-final-form-arrays#56]
### Are you submitting a **bug report** or a **feature request**?

bug report

### What is the current behavior?

Have a form that has a FieldArray in it. The form has initialValues set for the array.
If you use field.remove(index) to remove a row from the FieldArray, it does not make the parent form dirty.
This is an issue where the disabled of the submit button on the form is tied to "pristine".

The final form documentation at [https://github.com/final-form/react-final-form-arrays#simple-example](https://github.com/final-form/react-final-form-arrays#simple-example) has a link to a codesandbox at [https://codesandbox.io/s/kx8qv67nk5](https://codesandbox.io/s/kx8qv67nk5).
In this example, if you insert the following in the `<Form>` tag:
`      initialValues={{
        company: 'MinuteMe.com',
        customers: [
          {
            firstName: 'Simon',
            lastName: 'Steele'
          }
        ]
      }}
`
You will see the form Submit button is immediately disabled - form is pristine.
Delete the Customer row, and form becomes dirty - Submit button is enabled.

NOW... This sandbox uses old versions of the libraries.

I am using newer versions, per this sandbox [https://codesandbox.io/s/p34l93w81j](https://codesandbox.io/s/p34l93w81j). NOTE this sandbox already has my initialValues entered.

See that the same outcome is not achieved by deleting the row! The form is still dirty even though the row was removed.

### What is the expected behavior?

Expected behaviour is that the form should be marked 'dirty' when the array row is removed.

### Sandbox Link

See above.

### What's your environment?

The version that fails (per sandbox link above):
    "react-final-form-arrays": "1.1.0",
    "react-final-form": "3.6.7",
    "react-dom": "16.6.0",
    "react": "16.6.0",
    "final-form-arrays": "1.1.0",
    "final-form": "4.10.0"

**Comment by ncphillips** [comment]
We just confirmed this issue, and implemented isEquals as the combination length/identity check. 

I think it would be better if `FieldsArray` automatically took care of the length check, and the props version of `isEquals` was to compare items, and defaulted to identity comparison.

FieldsArray
```
isEquals(a, b,) {
  if (a.length != b.length) return false

  let isEquals = this.props.isEquals || ((a, b) => a === b)

  for (let i=0; i < a.length; i++) {
    if (isEquals(a[i], b[i])) return false
  }
  return true
}
```

**Comment by shun-liang** [comment]
Quoting @ncphillips 

> ...it would be better if FieldsArray automatically took care of the length check, and the props version of isEquals was to compare items, and defaulted to identity comparison.

May I ask if @erikras agrees too? Is this considered a bug, and will it ever be fixed? Many thanks.

**Comment by VincentCharpentier** [comment]
A fix for this bug would be really awesome 🙏

**Comment by PerfectPixel** [comment]
@VincentCharpentier Depending on your use-case this should be fixed in the newer version.

**Comment by erikras** [comment]
Yeah, I _think_ this is fixed now. The [`defaultIsEqual`](https://github.com/final-form/react-final-form-arrays/blob/master/src/defaultIsEqual.js) definitely includes a `length` check.

**Comment by VincentCharpentier** [comment]
I can confirm this is fixed with these versions:

```
"final-form": "4.16.1",
"final-form-arrays": "1.1.2",
"react-final-form": "6.3.0",
"react-final-form-arrays": "3.1.0",
```
