### ISSUE TITLE
FieldArrayProps is not defined in v2.0.2

### ISSUE THREAD

**Issue by ividic** [final-form/react-final-form-arrays#72]
### What is the current behavior?

Version 2.0.2 has a `FieldArrayProps is not defined` error, which is not there in 2.0.1

### Sandbox Link

Fork of the [Simple Example](https://codesandbox.io/s/kx8qv67nk5), with the latest version of react-final-form-arrays: https://codesandbox.io/s/lyrp6961jq

**Comment by newsiberian** [comment]
![screenshot_20190305_124829](https://user-images.githubusercontent.com/11130487/53783617-02931e00-3f45-11e9-9686-fc58582d0b54.png)

**Comment by ThiefMaster** [comment]
A quick fix for this would be nice, since this breaks stuff for anyone using caret/tilde versions

**Comment by stevepopovich** [comment]
You can lock the version to 2.0.1

**Comment by ThiefMaster** [comment]
Sure, my point was that a semver-patch version change should not break things as doing so requires ALL users to pin an exact version, and unpin it again later.

**Comment by cloneali** [comment]
@erikras any help with this breaking change?

**Comment by luishdz1010** [comment]
This makes me lose confidence on semver for this project

**Comment by crobinson42** [comment]
I don't see any issues with the src code - seems like it might be a bundling issue where the rollup flow plugin missed stripping our this `FieldArrayProps` flow type and the bundle was published. @erikras any help here?

**Comment by NateRadebaugh** [comment]
Any update here?

**Comment by rosskevin** [comment]
I PR'd the bundle fix in #74.
