### ISSUE TITLE
Upgrade react-final-form to v5: Remove use of `WithReactFinalForm`

### ISSUE THREAD

**Issue by jermspeaks** [final-form/react-final-form-arrays#77]
### Are you submitting a **bug report** or a **feature request**?

Feature Request: Upgrade `react-final-form` to v5.

[Deprecated in v5](https://github.com/final-form/react-final-form/releases/tag/v5.0.0)
> The previously exported `withReactFinalForm` HOC has been removed. Now you should use the `useForm()` hook if you'd like to get the 🏁 Final Form instance out of the context.

### What is the current behavior?

`react-final-form-arrays` cannot be used with v5 of `react-final-form`. Must downgrade to v4 until library is updated.

### What is the expected behavior?

Ability to use `react-final-form-arrays` with upgrade to new v5 `react-final-form` library.

### What's your environment?

n/a - for all environments

### Other information

Breaking change would mean `react-final-form-array` also needs a breaking change version bump.

**Comment by jermspeaks** [comment]
I thought this would be an easy fix, but it appears `react-final-form-arrays` is using lifecycle methods and the `WithReactFinalForm` as a HOC. `useForm` is a hook and doesn't work the same way.

I think it would also be wise if this upgrade is going to change `FieldArray` as a functional component.

**Comment by ThiefMaster** [comment]
I was hit by this issue as well when trying to update my project to use 5.1

**Comment by erikras** [comment]
Yes. This lib is not yet compatible with RFF5. Should be early next week before it is.

**Comment by erikras** [comment]
> I think it would also be wise if this upgrade is going to change FieldArray as a functional component.

Yep, gonna change this to hooks, too.

**Comment by eknowles** [comment]
thanks @erikras really appreciate it!

**Comment by VincentCharpentier** [comment]
Thanks for the hint @erikras .
Note that the current npm install instructions of the README won't work since it does not specify a version for RFF

**Comment by SpearThruster** [comment]
Any updates on this issue? So eager to try out react-final-form v5 but this is kinda a blocker. :D

**Comment by erikras** [comment]
Working on it. Getting close. It'll be published this week for sure.

**Comment by dmaklygin** [comment]
Thanks @erikras! Look forward :)
