### ISSUE TITLE
Typings for meta.error

### ISSUE THREAD

**Issue by xiavn** [final-form/react-final-form-arrays#78]
### Are you submitting a **bug report** or a **feature request**?

Bug

### What is the current behavior?

They typescript typings for the meta object currently list error as a boolean, but the docs suggest it should be any to match the final-form version. It looks like initial and submitError are also booleans as well.

I'm not sure if this is intended as I've only just started using the library, but from the examples it doesn't look like it should be a boolean. Sorry if I've made a mistake.

### What is the expected behavior?

The type should probably be any.

**Comment by netdown** [comment]
Any updates on this?

**Comment by erikras** [comment]
Published fix in [`v3.1.2`](https://github.com/final-form/react-final-form-arrays/releases/tag/v3.1.2).
