### ISSUE TITLE
useFieldArray isn't exported

### ISSUE THREAD

**Issue by uchwyt** [final-form/react-final-form-arrays#86]
### Are you submitting a **bug report** or a **feature request**?

bug report

### What is the current behavior?

Hook useFieldArray isn't exported from index

### What is the expected behavior?

It should be exported

### What's your environment?

    "final-form": "4.13.1",
    "final-form-arrays": "1.1.2",
    "react-final-form": "6.0.1",
    "react-final-form-arrays": "3.0.0",

**Comment by mafiurs** [comment]
You should try:
### **npm install react-final-form@latest --save**
I had a similar issue and updating **react-final-form** was the solution
