### ISSUE TITLE
.push regression in v3

### ISSUE THREAD

**Issue by TrejGun** [final-form/react-final-form-arrays#91]
### Are you submitting a **bug report** or a **feature request**?

bug report

### What is the current behavior?

after update to v3 push works different
in example it shows only one line instead of five

### What is the expected behavior?

example should show five lines

### Sandbox Link

https://codesandbox.io/s/react-final-form-field-arrays-dehxx

### What's your environment?

    "final-form": "4.16.1",
    "final-form-arrays": "1.1.2",
    "final-form-set-field-touched": "1.0.1",
    "final-form-submit-listener": "1.0.0",
    "react-final-form": "6.3.0",
    "react-final-form-arrays": "3.1.0",

chrome 75

**Comment by jvke** [comment]
This is fixed by changing the dependency of your useEffect fn to just `fields`: https://codesandbox.io/s/react-final-form-field-arrays-onrfv

**Comment by TrejGun** [comment]
oh i see) this works in your example. have not tested it in my project yet. thanks 🙏
