### ISSUE TITLE
Add ability to get field values

### ISSUE THREAD

**Issue by doytch** [final-form/react-final-form-arrays#95]
### Are you submitting a **bug report** or a **feature request**?

Feature Request

### What is the current behavior?

`FieldArray` components get a `fields` prop which is an object containing various methods.

### What is the expected behavior?

It'd be great if it were possible to get the values of those, similar to [redux-form's `fields.getAll()` functionality](https://redux-form.com/8.2.2/docs/api/fieldarray.md/#-code-fields-getall-function-code-).

I realise that many problems can be solved by rendering the `FieldArray`'s members as a `Field` and managing the value there. However, this pattern can be pretty ugly in some situations.

For example, here's [an HOC that uses `getAll()` in production](https://github.com/folio-org/stripes-erm-components/blob/c66a39248d203526c6eb02908493bd6b050d1458/lib/withKiwtFieldArray/withKiwtFieldArray.js). The point of that HOC is mainly to abstract away the complexity in how our backends handle array member deletion from form fields. The complexity is that when we want to delete an array member object, we need to send back an array that contains an object with the member's `id` and a `_delete` key set to `true`. 

The reason the backend operates that way is to basically support `PATCH`-like requests where an entire array doesn't need to be `PUT`, just the array members that have changed.

### Other information
Similar issue: https://github.com/final-form/react-final-form-arrays/issues/13

**Comment by JacobCooley** [comment]
+1 would love this as well

**Comment by erikras** [comment]
Ha! This is already there (it's used in tests), but is totally undocumented and untyped.

I'll remedy that shortly.

**Comment by erikras** [comment]
Published fix in [`v3.1.1`](https://github.com/final-form/react-final-form-arrays/releases/tag/v3.1.1).

**Comment by nvaken** [comment]
@erikras Is it possible when using `subscription={{}}` value will be undefined? Is that as designed?

**Comment by vufrontend** [comment]
@nvaken I think it is impossible. We have to subscription value to call fields.value. It's weird
