### ISSUE TITLE
New line appears and typing incorrect in last version 3.1.0

### ISSUE THREAD

**Issue by qvantor** [final-form/react-final-form-arrays#99]
### Are you submitting a **bug report** or a **feature request**?
Bug report

### What is the current behavior?
All libraries is up to date to last version
https://codesandbox.io/s/react-final-form-field-arrays-05nv1
* Add 3 customers
* Remove second customer
* Start type in any field of `Cust. #2`
* Unexpected behavior (third line appears and typing incorrect)

### What is the expected behavior?
In older version work's correctly
https://codesandbox.io/s/kx8qv67nk5

### What's your environment?
OS: MacOS Mojave
Browser: Chrome Version 75.0.3770.100

**Comment by likerRr** [comment]
+1 got this bug too. It's very annoying. Any workaround or temp fix for it? @erikras

**Comment by likerRr** [comment]
@erikras can you take a look on this issue? Library in it's latest release seems not usable.

**Comment by likerRr** [comment]
@erikras 13 days have passed since library is broken. [Why not to commit advertisement then](https://github.com/final-form/react-final-form-arrays/commit/10ee4b929a92b9ef961c690276d61fdeda7f0dfd)? :confused:

**Comment by oliverlaz** [comment]
Hi @erikras,
We got hit by this issue and we had to downgrade the versions.
Do you have a plan when this issue will be fixed? Maybe we can help if you provide us some pointers.

**Comment by BuBliC** [comment]
Hi folks!
It seems to me that you need to use **final-form-arrays@3.0.1** (in codesandbox example it's 3.0.0)

**Comment by qvantor** [comment]
@BuBliC switching to 3.0.1 fixed the issue!
